-- Run this once in a Snowsight worksheet (Projects > Worksheets > + SQL Worksheet).
-- 1) Replace <PASTE_PUBLIC_KEY_HERE> with the value printed by scripts/generate_keys.py
-- 2) Select all and click Run (or Ctrl/Cmd + Shift + Enter)

USE ROLE ACCOUNTADMIN;

-- Small warehouse that suspends itself after 60 s to save credits
CREATE WAREHOUSE IF NOT EXISTS WEATHER_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS WEATHER_DB;
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.RAW;        -- raw API data loaded by Airflow
CREATE SCHEMA IF NOT EXISTS WEATHER_DB.ANALYTICS;  -- dbt models

CREATE ROLE IF NOT EXISTS WEATHER_ROLE;
GRANT USAGE ON WAREHOUSE WEATHER_WH TO ROLE WEATHER_ROLE;
GRANT USAGE ON DATABASE WEATHER_DB TO ROLE WEATHER_ROLE;
GRANT ALL ON SCHEMA WEATHER_DB.RAW TO ROLE WEATHER_ROLE;
GRANT ALL ON SCHEMA WEATHER_DB.ANALYTICS TO ROLE WEATHER_ROLE;
GRANT ROLE WEATHER_ROLE TO ROLE SYSADMIN;

-- Service user for Airflow, dbt and Superset (key-pair login, no password/MFA prompts)
CREATE USER IF NOT EXISTS WEATHER_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = WEATHER_ROLE
  DEFAULT_WAREHOUSE = WEATHER_WH
  DEFAULT_NAMESPACE = WEATHER_DB.ANALYTICS
  RSA_PUBLIC_KEY = '<PASTE_PUBLIC_KEY_HERE>';

GRANT ROLE WEATHER_ROLE TO USER WEATHER_SVC;

-- Check: the RSA_PUBLIC_KEY_FP property should show a fingerprint
DESC USER WEATHER_SVC;
